name: spotify_eda
channels:
  - defaults
dependencies:
  - python==3.8.5
  - pandas
  - matplotlib
  - numpy
  - pip
  - jupyter
  - ipython
  - scikit-learn
  - seaborn
  - pycodestyle-magic # need to check if this actually works as a dependency in the yaml file, as it's not available through conda, only in pip